---
on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: '3.12'
          - version: '3.11'
          - version: '3.10'
          - version: '3.9'
            exclude-pattern-matching: true
          - version: '3.8'
            exclude-pattern-matching: true
    name: Python ${{ matrix.python.version }}
    steps:
      # Check out code
      - uses: actions/checkout@v4

      # Python
      - name: Setup python ${{ matrix.python.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install dev dependencies
        run: pip install --root-user-action=ignore --requirement requirements-dev.txt

      # Install library
      - name: Install maybe
        run: pip install --root-user-action=ignore --editable .

      # Tests
      - name: Run tests (excluding pattern matching)
        if: ${{ matrix.python.exclude-pattern-matching }}
        run: pytest --ignore=tests/test_pattern_matching.py
      - name: Run tests (including pattern matching)
        if: ${{ ! matrix.python.exclude-pattern-matching }}
        run: pytest

      # Linters
      - name: Run flake8 (excluding pattern matching)
        if: ${{ matrix.python.exclude-pattern-matching }}
        run: flake8 --extend-exclude tests/test_pattern_matching.py
      - name: Run flake8 (including pattern matching)
        if: ${{ ! matrix.python.exclude-pattern-matching }}
        run: flake8
      - name: Run mypy
        run: mypy

      # Packaging
      - name: Build packages
        run: |
          pip install --root-user-action=ignore --upgrade build pip setuptools wheel
          python -m build

      # Coverage
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4
        if: matrix.python == '3.9'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
